---
title: "implementacao_automatizada_completa"
output: html_document
date: "2026-05-16"
---

```{r}
library(tidyverse)
library(dplyr)
library(readxl)
library(quantmod)
library(stringr)
library(MASS)
library(ggplot2)
library(rugarch)
library(eva)
library(betategarch)
library(MSGARCH)
library(GAS)
```
#Dados
```{r}
data <- read_excel("economatica.xlsx", skip = 3, col_types = c("date", rep("numeric", 512)), na = c("", "-", NA)) |> 
  filter(Data > "2010-01-01" & Data < "2025-01-01") |> 
  filter(!if_all(where(is.numeric), is.na)) |> 
  select_if(~ !any(is.na(.))) |> 
  rename_with(~ str_remove(.x, "^(?s).*prov\n"), -Data)

nomes_colunas <- colnames(data)[-1]
```
```{r}
alpha1 <- 0.01
alpha2 <- 0.025
alpha3 <- 0.05
janela_dias <- 1500
```
```{r}
source("funcoes_especificacoes.R")
```

Implementação do VAR e do ES para todas as colunas
```{r}
for (coluna in nomes_colunas){
  #Retornos
  retornos <- data[[coluna]]
  
  #VAR paramétrico normal
  desvio_padrao <- sd(retornos, na.rm = TRUE)
  
  #VAr paramétrico t-student
  fit_student <- fitdistr(retornos, "t") #Ajusta uma distribuição t-student
  graus_de_liberdade <- fit_student$estimate["df"]
  
  #Matriz dos métodos de estimação do VAR
  numero_metodos_var <- 138
  VaR_matriz <- matrix(NA, nrow = (length(retornos) - janela_dias), ncol = numero_metodos_var)

  #Matriz dos_métodos de estimação do ES
  numero_metodos_es <- 138
  ES_matriz <- matrix(NA, nrow = (length(retornos) - janela_dias), ncol = numero_metodos_es)

  #Implementação
  for (i in 1:(length(retornos) - janela_dias)){
      print(coluna)
      print(i)
      mu = mean(retornos[i:(i + janela_dias -1)])
      janela <- scale(retornos[i:(i + janela_dias -1)], center = TRUE, scale = FALSE)
      x_vetor <- na.omit(as.numeric(janela))
      alphas <- c(alpha1, alpha2, alpha3)
      
      #MODELO GAS NORMAL
      fit_gas_n <- gas_fit(gas_spec_n, x_vetor)
      
      sigma_gn <- sqrt(fit_gas_n@GASDyn$mTheta[2, ]) 
      e_gn <- fit_gas_n@Data$vY / sigma_gn[1 : length(fit_gas_n@Data$vY)]
      sigma_fore_gn <- tail(sigma_gn, 1)
      
      pre_var_gn <- quantile(e_gn, prob = alphas)
      pre_es_gn  <- sapply(pre_var_gn, function(v) mean(e_gn[e_gn < v]))
      #filtrada
      var_gn     <- pre_var_gn * sigma_fore_gn
      es_gn      <- pre_es_gn * sigma_fore_gn
      #paramétrico
      var_par_gn <- as.numeric(tail(quantile(fit_gas_n, prob = alphas), 1))
      es_par_gn  <- as.numeric(tail(GAS::ES(fit_gas_n, prob = alphas), 1))
      
      gas_n_fore <- c(sigma_fore_gn, var_gn, es_gn, var_par_gn, es_par_gn)
      
      #MODELO GAS T-STUDENT
      fit_gas_t <- gas_fit(gas_spec_t, x_vetor)
      sigma_gt <- sqrt(fit_gas_t@GASDyn$mTheta[2, ] * fit_gas_t@GASDyn$mTheta[3, 1] /(fit_gas_t@GASDyn$mTheta[3, 1] - 2))
      e_gt <- fit_gas_t@Data$vY / sigma_gt[1 : length(fit_gas_t@Data$vY)]
      sigma_fore_gt <- tail(sigma_gt, 1)
      
      pre_var_gt <- quantile(e_gt, prob = alphas)
      pre_es_gt  <- sapply(pre_var_gt, function(v) mean(e_gt[e_gt < v]))
      
      var_gt     <- pre_var_gt * sigma_fore_gt
      es_gt      <- pre_es_gt * sigma_fore_gt
      var_par_gt <- as.numeric(tail(quantile(fit_gas_t, prob = alphas), 1))
      es_par_gt  <- as.numeric(tail(GAS::ES(fit_gas_t, prob = alphas), 1))
      
      gas_t_fore <- c(sigma_fore_gt, var_gt, es_gt, var_par_gt, es_par_gt)
      
      #MODELO MSGARCH NORMAL
      fit_ms_n <- msgarch_fit(ms_spec_n, x_vetor)
      
      e_msn <- fit_ms_n$data / Volatility(fit_ms_n)
      sigma_fore_msn <- predict(fit_ms_n, nahead = 1)$vol
      
      pre_var_msn <- quantile(e_msn, prob = alphas)
      pre_es_msn  <- sapply(pre_var_msn, function(v) mean(e_msn[e_msn < v]))
      
      var_msn     <- pre_var_msn * sigma_fore_msn
      es_msn      <- pre_es_msn * sigma_fore_msn
      var_es_msn  <- Risk(fit_ms_n, nahead = 1, alpha = alphas)
      var_par_msn <- var_es_msn$VaR
      es_par_msn  <- var_es_msn$ES
      
      ms_n_fore <- c(sigma_fore_msn, var_msn, es_msn, var_par_msn, es_par_msn)
      
      #MODELO MSGARCH T-STUDENT
      fit_ms_t <- msgarch_fit(ms_spec_t, x_vetor)
      
      e_mst <- fit_ms_t$data / Volatility(fit_ms_t)
      sigma_fore_mst <- predict(fit_ms_t, nahead = 1)$vol
      
      pre_var_mst <- quantile(e_mst, prob = alphas)
      pre_es_mst  <- sapply(pre_var_mst, function(v) mean(e_mst[e_mst < v]))
      
      var_mst     <- pre_var_mst * sigma_fore_mst
      es_mst      <- pre_es_mst * sigma_fore_mst
      var_es_mst  <- Risk(fit_ms_t, nahead = 1, alpha = alphas)
      var_par_mst <- var_es_mst$VaR
      es_par_mst  <- var_es_mst$ES
      
      ms_t_fore <- c(sigma_fore_mst, var_mst, es_mst, var_par_mst, es_par_mst)
      
    #----------------------------------------------------------------------------------
    
      # Simulação Histórica
      VaR_matriz[i, 1:3] <- sapply(c(alpha1, alpha2, alpha3), function(alpha) calc_VaR_hist(janela, alpha))
      ES_matriz[i, 1:3] <- sapply(c(alpha1, alpha2, alpha3), function(alpha) calc_ES_hist(janela, alpha))
      
      # VaR paramétrico Normal
      VaR_matriz[i, 4:6] <- sapply(c(alpha1, alpha2, alpha3), function(alpha) mu + desvio_padrao * qnorm(alpha))
      ES_matriz[i, 4:6] <- sapply(c(alpha1, alpha2, alpha3), function(alpha) es_gauss(janela, alpha))
    
      # VaR Paramétrico T-Student
      VaR_matriz[i, 7:9] <- sapply(c(alpha1, alpha2, alpha3), function(alpha) mu + desvio_padrao * qt(alpha, graus_de_liberdade))
      ES_matriz[i, 7:9] <- sapply(c(alpha1, alpha2, alpha3), function(alpha) es_student(janela, alpha))
      
      # GARCH(1,1) Norm
      fit_garch1 <- garch_fit(especificacao1, (janela - mean(janela)))
      if (!is.null(fit_garch1)) {
        sigma_fore1 <- as.numeric(ugarchforecast(fit_garch1, n.ahead = 1)@forecast$sigmaFor)
        VaR_matriz[i, 10:12] <- mu + qdist("norm", c(alpha1, alpha2, alpha3), mu = 0, sigma = sigma_fore1)
        ES_matriz[i, 10:12] <- mu - sigma_fore1 * dnorm(qnorm(c(alpha1, alpha2, alpha3))) / c(alpha1, alpha2, alpha3)
        # FHS
        VaR_matriz[i, 46:48] <- mu + sapply(c(alpha1, alpha2, alpha3), function(alpha) quantile(janela / sigma(fit_garch1), alpha) * sigma_fore1)
        ES_matriz[i, 46] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 46]]) 
        ES_matriz[i, 47] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 47]])
        ES_matriz[i, 48] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 48]]) 
      }
    
      # GARCH(1,1) Std
      fit_garch2 <- garch_fit(especificacao2, (janela - mean(janela)))
      if (!is.null(fit_garch2)) {
        sigma_fore2 <- as.numeric(ugarchforecast(fit_garch2, n.ahead = 1)@forecast$sigmaFor)
        nu2 <- coef(fit_garch2)["shape"]
        k2 <- sqrt(nu2 / (nu2 - 2))
        VaR_matriz[i, 13:15] <- mu + (sigma_fore2 * qt(c(alpha1, alpha2, alpha3), df = nu2) / k2)
        ES_matriz[i, 13:15] <- mu - (sigma_fore2 / k2) * (dt(qt(c(alpha1, alpha2, alpha3), df = nu2), df = nu2) / c(alpha1, alpha2, alpha3)) * ((nu2 + qt(c(alpha1, alpha2, alpha3), df = nu2)^2) / (nu2 - 1))
        # FHS
        VaR_matriz[i, 49:51] <- mu + sapply(c(alpha1, alpha2, alpha3), function(alpha) quantile(janela / sigma(fit_garch2), alpha) * sigma_fore2)
        ES_matriz[i, 49] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 49]])
        ES_matriz[i, 50] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 50]]) 
        ES_matriz[i, 51] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 51]]) 
      }
    
      # eGARCH(1,1) Norm
      fit_garch3 <- garch_fit(especificacao3, (janela - mean(janela)))
      if (!is.null(fit_garch3)) {
        sigma_fore3 <- as.numeric(ugarchforecast(fit_garch3, n.ahead = 1)@forecast$sigmaFor)
        VaR_matriz[i, 16:18] <- mu + qdist("norm", c(alpha1, alpha2, alpha3), mu = 0, sigma = sigma_fore3)
        ES_matriz[i, 16:18] <- mu - sigma_fore3 * dnorm(qnorm(c(alpha1, alpha2, alpha3))) / c(alpha1, alpha2, alpha3)
        # FHS
        VaR_matriz[i, 52:54] <- mu + sapply(c(alpha1, alpha2, alpha3), function(alpha) quantile(janela / sigma(fit_garch3), alpha) * sigma_fore3)
        ES_matriz[i, 52] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 52]])
        ES_matriz[i, 53] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 53]])
        ES_matriz[i, 54] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 54]]) 
      }
    
      # eGARCH(1,1) Std
      fit_garch4 <- garch_fit(especificacao4, (janela - mean(janela)))
      if (!is.null(fit_garch4)) {
        sigma_fore4 <- as.numeric(ugarchforecast(fit_garch4, n.ahead = 1)@forecast$sigmaFor)
        nu4 <- coef(fit_garch4)["shape"]
        k4 <- sqrt(nu4 / (nu4 - 2))
        VaR_matriz[i, 19:21] <- mu + (sigma_fore4 * qt(c(alpha1, alpha2, alpha3), df = nu4) / k4)
        ES_matriz[i, 19:21] <- mu - (sigma_fore4 / k4) * (dt(qt(c(alpha1, alpha2, alpha3), df = nu4), df = nu4) / c(alpha1, alpha2, alpha3)) * ((nu4 + qt(c(alpha1, alpha2, alpha3), df = nu4)^2) / (nu4 - 1))
        # FHS
        VaR_matriz[i, 55:57] <- mu + sapply(c(alpha1, alpha2, alpha3), function(alpha) quantile(janela / sigma(fit_garch4), alpha) * sigma_fore4)
        ES_matriz[i, 55] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 55]])
        ES_matriz[i, 56] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 56]]) 
        ES_matriz[i, 57] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 57]])
      }
    
      # iGARCH(1,1) Norm
      fit_garch5 <- garch_fit(especificacao5, (janela - mean(janela)))
      if (!is.null(fit_garch5)) {
        sigma_fore5 <- as.numeric(ugarchforecast(fit_garch5, n.ahead = 1)@forecast$sigmaFor)
        VaR_matriz[i, 22:24] <- mu + qdist("norm", c(alpha1, alpha2, alpha3), mu = 0, sigma = sigma_fore5)
        ES_matriz[i, 22:24] <- mu - sigma_fore5 * dnorm(qnorm(c(alpha1, alpha2, alpha3))) / c(alpha1, alpha2, alpha3)
        # FHS
        VaR_matriz[i, 58:60] <- mu + sapply(c(alpha1, alpha2, alpha3), function(alpha) quantile(janela / sigma(fit_garch5), alpha) * sigma_fore5)
        ES_matriz[i, 58] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 58]]) 
        ES_matriz[i, 59] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 59]])
        ES_matriz[i, 60] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 60]])
      }
    
      # iGARCH(1,1) Std
      fit_garch6 <- garch_fit(especificacao6, (janela - mean(janela)))
      if (!is.null(fit_garch6)) {
        sigma_fore6 <- as.numeric(ugarchforecast(fit_garch6, n.ahead = 1)@forecast$sigmaFor)
        nu6 <- coef(fit_garch6)["shape"]
        k6 <- sqrt(nu6 / (nu6 - 2))
        VaR_matriz[i, 25:27] <- mu + (sigma_fore6 * qt(c(alpha1, alpha2, alpha3), df = nu6) / k6)
        ES_matriz[i, 25:27] <- mu - (sigma_fore6 / k6) * (dt(qt(c(alpha1, alpha2, alpha3), df = nu6), df = nu6) / c(alpha1, alpha2, alpha3)) * ((nu6 + qt(c(alpha1, alpha2, alpha3), df = nu6)^2) / (nu6 - 1))
        # FHS
        VaR_matriz[i, 61:63] <- mu + sapply(c(alpha1, alpha2, alpha3), function(alpha) quantile(janela / sigma(fit_garch6), alpha) * sigma_fore6)
        ES_matriz[i, 61] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 61]]) 
        ES_matriz[i, 62] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 62]]) 
        ES_matriz[i, 63] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 63]]) 
      }
    
      # fiGARCH(1,1) Norm
      fit_garch7 <- garch_fit(especificacao7, (janela - mean(janela)))
      if (!is.null(fit_garch7)) {
        sigma_fore7 <- as.numeric(ugarchforecast(fit_garch7, n.ahead = 1)@forecast$sigmaFor)
        VaR_matriz[i, 28:30] <- mu + qdist("norm", c(alpha1, alpha2, alpha3), mu = 0, sigma = sigma_fore7)
        ES_matriz[i, 28:30] <- mu - sigma_fore7 * dnorm(qnorm(c(alpha1, alpha2, alpha3))) / c(alpha1, alpha2, alpha3)
        # FHS
        VaR_matriz[i, 64:66] <- mu + sapply(c(alpha1, alpha2, alpha3), function(alpha) quantile(janela / sigma(fit_garch7), alpha) * sigma_fore7)
        ES_matriz[i, 64] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 64]]) 
        ES_matriz[i, 65] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 65]]) 
        ES_matriz[i, 66] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 66]]) 
      }
    
      # fiGARCH(1,1) Std
      fit_garch8 <- garch_fit(especificacao8, (janela - mean(janela)))
      if (!is.null(fit_garch8)) {
        sigma_fore8 <- as.numeric(ugarchforecast(fit_garch8, n.ahead = 1)@forecast$sigmaFor)
        nu8 <- coef(fit_garch8)["shape"]
        k8 <- sqrt(nu8 / (nu8 - 2))
        VaR_matriz[i, 31:33] <- mu + (sigma_fore8 * qt(c(alpha1, alpha2, alpha3), df = nu8) / k8)
        ES_matriz[i, 31:33] <- mu - (sigma_fore8 / k8) * (dt(qt(c(alpha1, alpha2, alpha3), df = nu8), df = nu8) / c(alpha1, alpha2, alpha3)) * ((nu8 + qt(c(alpha1, alpha2, alpha3), df = nu8)^2) / (nu8 - 1))
        # FHS
        VaR_matriz[i, 67:69] <- mu + sapply(c(alpha1, alpha2, alpha3), function(alpha) quantile(janela / sigma(fit_garch8), alpha) * sigma_fore8)
        ES_matriz[i, 67] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 67]])
        ES_matriz[i, 68] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 68]])
        ES_matriz[i, 69] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 69]]) 
      }
    
      # sGARCH(1,1) Norm
      fit_garch9 <- garch_fit(especificacao9, (janela - mean(janela)))
      if (!is.null(fit_garch9)) {
        sigma_fore9 <- as.numeric(ugarchforecast(fit_garch9, n.ahead = 1)@forecast$sigmaFor)
        VaR_matriz[i, 34:36] <- mu + qdist("norm", c(alpha1, alpha2, alpha3), mu = 0, sigma = sigma_fore9)
        ES_matriz[i, 34:36] <- mu - sigma_fore9 * dnorm(qnorm(c(alpha1, alpha2, alpha3))) / c(alpha1, alpha2, alpha3)
        # FHS
        VaR_matriz[i, 70:72] <- mu + sapply(c(alpha1, alpha2, alpha3), function(alpha) quantile(janela / sigma(fit_garch9), alpha) * sigma_fore9)
        ES_matriz[i, 70] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 70]])
        ES_matriz[i, 71] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 71]]) 
        ES_matriz[i, 72] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 72]]) 
      }
    
      # sGARCH(1,1) Std
      fit_garch10 <- garch_fit(especificacao10, (janela - mean(janela)))
      if (!is.null(fit_garch10)) {
        sigma_fore10 <- as.numeric(ugarchforecast(fit_garch10, n.ahead = 1)@forecast$sigmaFor)
        nu10 <- coef(fit_garch10)["shape"]
        k10 <- sqrt(nu10 / (nu10 - 2))
        VaR_matriz[i, 37:39] <- mu + (sigma_fore10 * qt(c(alpha1, alpha2, alpha3), df = nu10) / k10)
        ES_matriz[i, 37:39] <- mu - (sigma_fore10 / k10) * (dt(qt(c(alpha1, alpha2, alpha3), df = nu10), df = nu10) / c(alpha1, alpha2, alpha3)) * ((nu10 + qt(c(alpha1, alpha2, alpha3), df = nu10)^2) / (nu10 - 1))
        # FHS
        VaR_matriz[i, 73:75] <- mu + sapply(c(alpha1, alpha2, alpha3), function(alpha) quantile(janela / sigma(fit_garch10), alpha) * sigma_fore10)
        ES_matriz[i, 73] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 73]]) 
        ES_matriz[i, 74] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 74]]) 
        ES_matriz[i, 75] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 75]])
      }
    
      # NGARCH(1,1) Norm
      fit_garch11 <- garch_fit(especificacao11, (janela - mean(janela)))
      if (!is.null(fit_garch11)) {
        sigma_fore11 <- as.numeric(ugarchforecast(fit_garch11, n.ahead = 1)@forecast$sigmaFor)
        VaR_matriz[i, 40:42] <- mu + qdist("norm", c(alpha1, alpha2, alpha3), mu = 0, sigma = sigma_fore11)
        ES_matriz[i, 40:42] <- mu - sigma_fore11 * dnorm(qnorm(c(alpha1, alpha2, alpha3))) / c(alpha1, alpha2, alpha3)
        # FHS
        VaR_matriz[i, 76:78] <- mu + sapply(c(alpha1, alpha2, alpha3), function(alpha) quantile(janela / sigma(fit_garch11), alpha) * sigma_fore11)
        ES_matriz[i, 76] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 76]])
        ES_matriz[i, 77] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 77]]) 
        ES_matriz[i, 78] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 78]]) 
      }
    
      # NGARCH(1,1) Std
      fit_garch12 <- garch_fit(especificacao12, (janela - mean(janela)))
      if (!is.null(fit_garch12)) {
        sigma_fore12 <- as.numeric(ugarchforecast(fit_garch12, n.ahead = 1)@forecast$sigmaFor)
        nu12 <- coef(fit_garch12)["shape"]
        k12 <- sqrt(nu12 / (nu12 - 2))
        VaR_matriz[i, 43:45] <- mu + (sigma_fore12 * qt(c(alpha1, alpha2, alpha3), df = nu12) / k12)
        ES_matriz[i, 43:45] <- mu - (sigma_fore12 / k12) * (dt(qt(c(alpha1, alpha2, alpha3), df = nu12), df = nu12) / c(alpha1, alpha2, alpha3)) * ((nu12 + qt(c(alpha1, alpha2, alpha3), df = nu12)^2) / (nu12 - 1))
        # FHS
        VaR_matriz[i, 79:81] <- mu + sapply(c(alpha1, alpha2, alpha3), function(alpha) quantile(janela / sigma(fit_garch12), alpha) * sigma_fore12)
        ES_matriz[i, 79] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 79]]) 
        ES_matriz[i, 80] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 80]]) 
        ES_matriz[i, 81] <- mean(retornos[i:(i + janela_dias -1)][retornos[i:(i + janela_dias -1)] <= VaR_matriz[i, 81]]) 
      }
      
      # MODELO CAViaR ASSIMÉTRICO
      VaR_matriz[i, 82:84] <- sapply(c(alpha1, alpha2, alpha3), function(alpha) tail(CAViaR(janela, risklevel = alpha, type = "asym_slope")[[1]], 1))
      ES_matriz[i, 82] <- mean(janela[janela <= VaR_matriz[i, 82]])
      ES_matriz[i, 83] <- mean(janela[janela <= VaR_matriz[i, 83]])
      ES_matriz[i, 84] <- mean(janela[janela <= VaR_matriz[i, 84]])
    
      # MODELO CAViaR SIMÉTRICO
      VaR_matriz[i, 85:87] <- sapply(c(alpha1, alpha2, alpha3), function(alpha) tail(CAViaR(janela, risklevel = alpha, type = "sym_abs")[[1]], 1))
      ES_matriz[i, 85] <- mean(janela[janela <= VaR_matriz[i, 85]])
      ES_matriz[i, 86] <- mean(janela[janela <= VaR_matriz[i, 86]])
      ES_matriz[i, 87] <- mean(janela[janela <= VaR_matriz[i, 87]])
    
      # TEORIA DOS VALORES EXTREMOS
      VaR_matriz[i, 88:90] <- sapply(c(alpha1,alpha2,alpha3), function(alpha) evt(alpha, janela))
      ES_matriz[i, 88:90] <- sapply(c(alpha1,alpha2,alpha3), function(alpha) evt_ES(alpha, janela))
      
      
      #GAS Normal
      VaR_matriz[i, 91:93] <- mu + gas_n_fore[2:4]    
      VaR_matriz[i, 94:96] <- mu + gas_n_fore[8:10]  
      ES_matriz[i, 91:93]  <- mu + gas_n_fore[5:7]    
      ES_matriz[i, 94:96]  <- mu + gas_n_fore[11:13]  
      
      #GAS Student-t
      VaR_matriz[i, 97:99]   <- mu + gas_t_fore[2:4]
      VaR_matriz[i, 100:102] <- mu + gas_t_fore[8:10]
      ES_matriz[i, 97:99]    <- mu + gas_t_fore[5:7]
      ES_matriz[i, 100:102]  <- mu + gas_t_fore[11:13]
      
      #MSGARCH Normal
      VaR_matriz[i, 103:105] <- mu + ms_n_fore[2:4]
      VaR_matriz[i, 106:108] <- mu + ms_n_fore[8:10]
      ES_matriz[i, 103:105]  <- mu + ms_n_fore[5:7]
      ES_matriz[i, 106:108]  <- mu + ms_n_fore[11:13]
      
      #MSGARCH Student-t
      VaR_matriz[i, 109:111] <- mu + ms_t_fore[2:4]
      VaR_matriz[i, 112:114] <- mu + ms_t_fore[8:10]
      ES_matriz[i, 109:111]  <- mu + ms_t_fore[5:7]
      ES_matriz[i, 112:114]  <- mu + ms_t_fore[11:13]

      # GARCH FITs
      # FITS DO GJR-GARCH
      fit_gjr_n <- ugarchfit(especificacao_gjr_n, (janela - mean(janela)), solver = 'hybrid')
      fit_gjr_t <- ugarchfit(especificacao_gjr_t, (janela - mean(janela)), solver = 'hybrid')

      #MODELO BETA-T-EGARCH (GAS)
      # Com Alavancagem e Com 2 Componentes
      fit_beta_asym  <- tegarch(x_vetor, asym = TRUE)
      fit_beta_2comp <- tegarch(x_vetor, components = 2)
      
      sigma_fore_asym  <- as.numeric(predict(fit_beta_asym, n.ahead = 1))
      sigma_fore_2comp <- as.numeric(predict(fit_beta_2comp, n.ahead = 1))
      
      df_asym  <- fit_beta_asym$par["df"]
      df_2comp <- fit_beta_2comp$par["df"]
      
      k_asym  <- sqrt(df_asym / (df_asym - 2))
      k_2comp <- sqrt(df_2comp / (df_2comp - 2))
      
        
      # GJR-GARCH(1,1) Distribuição Normal Paramétrico
      sigma_fore_gjr_n <- as.numeric(ugarchforecast(fit_gjr_n, n.ahead = 1)@forecast$sigmaFor)
      VaR_matriz[i, 115:117] <- mu + qdist("norm", c(alpha1, alpha2, alpha3), mu = 0, sigma = sigma_fore_gjr_n)
      ES_matriz[i, 115:117] <- mu - sigma_fore_gjr_n * dnorm(qnorm(c(alpha1, alpha2, alpha3))) / c(alpha1, alpha2, alpha3)
      
      # GJR-GARCH(1,1) Distribuição Student Paramétrico
      sigma_fore_gjr_t <- as.numeric(ugarchforecast(fit_gjr_t, n.ahead = 1)@forecast$sigmaFor)
      nu_gjr <- coef(fit_gjr_t)["shape"]
      k_gjr <- sqrt(nu_gjr / (nu_gjr - 2))
      VaR_matriz[i, 118:120] <- mu + (sigma_fore_gjr_t * qt(c(alpha1, alpha2, alpha3), df = nu_gjr) / k_gjr)
      ES_matriz[i, 118:120] <- mu - (sigma_fore_gjr_t / k_gjr) * (dt(qt(c(alpha1, alpha2, alpha3), df = nu_gjr), df = nu_gjr) / c(alpha1, alpha2, alpha3)) * ((nu_gjr + qt(c(alpha1, alpha2, alpha3), df = nu_gjr)^2) / (nu_gjr - 1))
      
      # GJR-GARCH(1,1) Distribuição Normal FHS
      VaR_matriz[i, 121:123] <- mu + sapply(c(alpha1, alpha2, alpha3), function(alpha) quantile(janela / sigma(fit_gjr_n), alpha) * sigma_fore_gjr_n)
      ES_matriz[i, 121:123] <- mu + sapply(c(alpha1, alpha2, alpha3), function(alpha) mean((janela / sigma(fit_gjr_n))[(janela / sigma(fit_gjr_n)) < quantile(janela / sigma(fit_gjr_n), alpha)], na.rm = TRUE) * sigma_fore_gjr_n)

      
      # GJR-GARCH(1,1) Distribuição Student FHS
      VaR_matriz[i, 124:126] <- mu + sapply(c(alpha1, alpha2, alpha3), function(alpha) quantile(janela / sigma(fit_gjr_t), alpha) * sigma_fore_gjr_t)
      ES_matriz[i, 124:126] <- mu + sapply(c(alpha1, alpha2, alpha3), function(alpha) mean((janela / sigma(fit_gjr_t))[(janela / sigma(fit_gjr_t)) < quantile(janela / sigma(fit_gjr_t), alpha)], na.rm = TRUE) * sigma_fore_gjr_t)
    
      
      #GAS Alavancagem
      VaR_matriz[i, 127:129] <- mu + (sigma_fore_asym * qt(alphas, df = df_asym) / k_asym)
      ES_matriz[i, 127:129]  <- mu - (sigma_fore_asym / k_asym) * (dt(qt(alphas, df = df_asym), df = df_asym) / alphas) * ((df_asym + qt(alphas, df = df_asym)^2) / (df_asym - 1))
      
      # GAS Dois Componentes
      VaR_matriz[i, 130:132] <- mu + (sigma_fore_2comp * qt(alphas, df = df_2comp) / k_2comp)
      ES_matriz[i, 130:132]  <- mu - (sigma_fore_2comp / k_2comp) * (dt(qt(alphas, df = df_2comp), df = df_2comp) / alphas) * ((df_2comp + qt(alphas, df = df_2comp)^2) / (df_2comp - 1))
      
      #Alavancagem FHS
      res_pad_asym <- x_vetor / fitted(fit_beta_asym)
      VaR_matriz[i, 133:135] <- mu + sapply(alphas, function(a) quantile(res_pad_asym, a) * sigma_fore_asym)
      ES_matriz[i, 133:135] <- mu + sapply(alphas, function(a) mean(res_pad_asym[res_pad_asym < quantile(res_pad_asym, a)], na.rm = TRUE) * sigma_fore_asym)
      
      #Dois Componentes FHS
      res_pad_2comp <- x_vetor / fitted(fit_beta_2comp)
      VaR_matriz[i, 136:138] <- mu + sapply(alphas, function(a) quantile(res_pad_2comp, a) * sigma_fore_2comp)
      ES_matriz[i, 136:138] <- mu + sapply(alphas, function(a) mean(res_pad_2comp[res_pad_2comp < quantile(res_pad_2comp, a)], na.rm = TRUE) * sigma_fore_2comp)
      
    }
  
  #Exportar resultados
  write.csv(VaR_matriz, paste0("VaR_metodosfinais_", coluna, ".csv"), row.names = FALSE)
  write.csv(ES_matriz, paste0("ES_metodosfinais_", coluna, ".csv"), row.names = FALSE)

}
```





























